"""update relationships

Revision ID: 00d44ae5738b
Revises: 170c14cdcad2
Create Date: 2025-03-20 08:43:42.319319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d44ae5738b'
down_revision: Union[str, None] = '170c14cdcad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_doctor_association',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'doctor_id')
    )
    op.drop_constraint('services_doctor_id_fkey', 'services', type_='foreignkey')
    op.drop_column('services', 'doctor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('services_doctor_id_fkey', 'services', 'doctors', ['doctor_id'], ['id'])
    op.drop_table('service_doctor_association')
    # ### end Alembic commands ###
