"""связывание доктора с юзером для чатов

Revision ID: 127230a45b98
Revises: 6daa504134e6
Create Date: 2025-05-30 10:06:50.334841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127230a45b98'
down_revision: Union[str, None] = '6daa504134e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'item_id', 'item_type')
    )
    op.add_column('chats', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'doctors', ['doctor_id'], ['id'])
    op.add_column('users', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['doctor_id'])
    op.create_foreign_key(None, 'users', 'doctors', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'doctor_id')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'doctor_id')
    op.drop_table('user_favorites')
    # ### end Alembic commands ###
