"""update models

Revision ID: 3da099798844
Revises: 64b654907e30
Create Date: 2025-03-14 11:01:03.086142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da099798844'
down_revision: Union[str, None] = '64b654907e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('work_time', sa.Text(), nullable=True))
    op.add_column('clinics', sa.Column('year_foundation', sa.Integer(), nullable=True))
    op.add_column('clinics', sa.Column('customers_count', sa.Integer(), nullable=True))
    op.add_column('clinics', sa.Column('reviews_count', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('experience', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('customer_count', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('reviews_count', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('blood_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blood_type')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'age')
    op.drop_column('users', 'photo_url')
    op.drop_column('services', 'logo_url')
    op.drop_column('doctors', 'reviews_count')
    op.drop_column('doctors', 'customer_count')
    op.drop_column('doctors', 'experience')
    op.drop_column('clinics', 'reviews_count')
    op.drop_column('clinics', 'customers_count')
    op.drop_column('clinics', 'year_foundation')
    op.drop_column('clinics', 'work_time')
    # ### end Alembic commands ###
