"""Правки по месседжу

Revision ID: dd7addc8f56b
Revises: 29bef0b77ce8
Create Date: 2025-04-11 12:29:52.024631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd7addc8f56b'
down_revision: Union[str, None] = '29bef0b77ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'status',
               existing_type=postgresql.ENUM('SENT', 'DELIVERED', 'READ', name='messagestatus'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('SENT', 'DELIVERED', 'READ', name='messagestatus'),
               existing_nullable=True)
    # ### end Alembic commands ###
